CREATE TABLE SYS_USER
(
	ID BIGINT NOT NULL AUTO_INCREMENT COMMENT '编号',
	LOGIN_NAME VARCHAR(100) NOT NULL COMMENT '登录名',
	PASSWORD VARCHAR(100) NOT NULL COMMENT '密码',
	NAME VARCHAR(100) NOT NULL COMMENT '姓名',
	EMAIL VARCHAR(200) COMMENT '邮箱',
	PHONE VARCHAR(200) COMMENT '电话',
	LOGIN_IP VARCHAR(100) COMMENT '最后登陆IP',
	LOGIN_DATE DATETIME COMMENT '最后登陆时间',
	PRIMARY KEY (ID)
) COMMENT = '用户表';

DROP TABLE IF EXISTS `blog_post`;
CREATE TABLE `blog_post` (
`ID`  bigint(20) NOT NULL AUTO_INCREMENT COMMENT '文章ID' ,
`USER_ID`  bigint(20) NOT NULL COMMENT '文章作者' ,
`PUBLIC_DATE`  datetime NULL DEFAULT NULL COMMENT '发布时间' ,
`CONTENT`  varchar(15535) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL COMMENT '文章内容' ,
`POST_TITLE`  varchar(100) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL COMMENT '文章标题' ,
`STATUS`  char(1) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT '1' COMMENT '文章状态（1：正常；0：删除）' ,
`POST_MODIFIED`  datetime NULL DEFAULT NULL COMMENT '修改时间' ,
`MENU_ORDER`  int(11) NULL DEFAULT NULL COMMENT '排序' ,
`COMMENT_COUNT`  int(11) NULL DEFAULT NULL COMMENT '评论条数' ,
`URL`  varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL ,
`LIKING`  int(11) NULL DEFAULT NULL ,
`CLICK_COUNT`  int(11) NULL DEFAULT NULL COMMENT '点击量' ,
`TERM_ID`  bigint(20) NOT NULL COMMENT '所属分类' ,
PRIMARY KEY (`ID`)
)
ENGINE=InnoDB
DEFAULT CHARACTER SET=utf8 COLLATE=utf8_general_ci
COMMENT='文章表'
AUTO_INCREMENT=99
;

CREATE TABLE BLOG_TAG(
	ID BIGINT NOT NULL AUTO_INCREMENT COMMENT 'ID',
	NAME VARCHAR(100) NOT NULL COMMENT '标签名字',
	PRIMARY KEY (ID)
) COMMENT = '标签表';

CREATE TABLE BLOG_TAG_POST(
	POST_ID BIGINT NOT NULL COMMENT '文章编号',
	TAG_ID BIGINT NOT NULL COMMENT '标签编号',
	PRIMARY KEY (POST_ID, TAG_ID)
) COMMENT = '文章标签表';

CREATE TABLE BLOG_TERM(
	ID BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键',
	NAME VARCHAR(100) NOT NULL COMMENT '名字',
	IS_SHOW CHAR(1) DEFAULT '0' NOT NULL COMMENT '是否在导航栏中显示（0：正常；1：不显示）',
	IS_PAGE CHAR(1) DEFAULT '0' NOT NULL COMMENT '是否是一个页面（0：是；1：不是）',
	PRIMARY KEY (ID)
) COMMENT = '分类表';


CREATE TABLE BLOG_PROJECTS
(
	ID BIGINT NOT NULL AUTO_INCREMENT COMMENT '编号',
	CONTENT VARCHAR(3000) NOT NULL COMMENT '内容',
	PRIMARY KEY (ID)
) COMMENT = '项目表';

CREATE TABLE BLOG_ABOUT
(
	ID BIGINT NOT NULL AUTO_INCREMENT COMMENT '编号',
	CONTENT VARCHAR(3000) NOT NULL COMMENT '内容',
	PRIMARY KEY (ID)
) COMMENT = '关于表';

-- ----------------------------
-- Table structure for `blog_link`
-- ----------------------------
DROP TABLE IF EXISTS `blog_link`;
CREATE TABLE `blog_link` (
`ID`  bigint(20) NOT NULL AUTO_INCREMENT ,
`NAME`  varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL ,
`URL`  varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL ,
PRIMARY KEY (`ID`)
)
ENGINE=InnoDB
DEFAULT CHARACTER SET=utf8 COLLATE=utf8_general_ci
AUTO_INCREMENT=2
;

-- ----------------------------
-- Table structure for `blog_term`
-- ----------------------------
DROP TABLE IF EXISTS `blog_term`;
CREATE TABLE `blog_term` (
`ID`  bigint(20) NOT NULL AUTO_INCREMENT COMMENT '主键' ,
`NAME`  varchar(100) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL COMMENT '名字' ,
`IS_SHOW`  char(1) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT '0' COMMENT '是否在导航栏中显示（0：正常；1：不显示）' ,
`STATUS`  char(255) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT '1' ,
`IS_PAGE`  char(1) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT '0' COMMENT '是否是一个页面（0：是；1：不是）' ,
PRIMARY KEY (`ID`))
ENGINE=InnoDB
DEFAULT CHARACTER SET=utf8 COLLATE=utf8_general_ci
COMMENT='分类表'
AUTO_INCREMENT=14
;



INSERT INTO `BLOG_PROJECTS` VALUES (1, 'hello world');
INSERT INTO `BLOG_ABOUT` VALUES (1, 'hello world');
INSERT INTO `sys_user` VALUES (1, 'admin', 'admin', 'admin', NULL, NULL, NULL, NULL);
INSERT INTO `blog_post` VALUES (1, 1, '2015-5-6 01:24:17', 'hello world~ have fun~', 'hello world', '1', '2015-5-6 01:24:40', NULL, 1, 'helloworld', 1, 1, 1);
INSERT INTO `blog_term` VALUES (1, '文章', '0','1', '0');
